var importedModes = false;

export default {
    /**
     * Import all Ace Components at once. BE CAREFUL! As this is a really heavy task.
     */
    async importHeavyItems() {
        await import("vue2-ace-editor");
        await this.importAceModes();
    },

    /**
     * Import all Ace Modes at once. BE CAREFUL! As this sums up to +6MB in total size
     */
    async importAceModes() {
        if (importedModes) return;
        importedModes = true;

        await import("brace/mode/ada");
        await import("brace/mode/applescript");
        await import("brace/mode/apache_conf");
        await import("brace/mode/asciidoc");
        await import("brace/mode/assembly_x86");
        await import("brace/mode/autohotkey");
        await import("brace/mode/batchfile");
        await import("brace/mode/bro");
        await import("brace/mode/c9search");
        await import("brace/mode/c_cpp");
        await import("brace/mode/cirru");
        await import("brace/mode/clojure");
        await import("brace/mode/cobol");
        await import("brace/mode/coffee");
        await import("brace/mode/coldfusion");
        await import("brace/mode/csharp");
        await import("brace/mode/css");
        await import("brace/mode/curly");
        await import("brace/mode/dart");
        await import("brace/mode/django");
        await import("brace/mode/d");
        await import("brace/mode/dockerfile");
        await import("brace/mode/dot");
        await import("brace/mode/drools");
        await import("brace/mode/eiffel");
        await import("brace/mode/ejs");
        await import("brace/mode/elixir");
        await import("brace/mode/elm");
        await import("brace/mode/erlang");
        await import("brace/mode/forth");
        await import("brace/mode/fortran");
        await import("brace/mode/ftl");
        await import("brace/mode/gcode");
        await import("brace/mode/gherkin");
        await import("brace/mode/gitignore");
        await import("brace/mode/glsl");
        await import("brace/mode/gobstones");
        await import("brace/mode/golang");
        await import("brace/mode/groovy");
        await import("brace/mode/haml");
        await import("brace/mode/handlebars");
        await import("brace/mode/haskell_cabal");
        await import("brace/mode/haskell");
        await import("brace/mode/haxe");
        await import("brace/mode/hjson");
        await import("brace/mode/html_elixir");
        await import("brace/mode/html");
        await import("brace/mode/html_ruby");
        await import("brace/mode/ini");
        await import("brace/mode/io");
        await import("brace/mode/jack");
        await import("brace/mode/jade");
        await import("brace/mode/java");
        await import("brace/mode/javascript");
        await import("brace/mode/jsoniq");
        await import("brace/mode/json");
        await import("brace/mode/jsp");
        await import("brace/mode/jsx");
        await import("brace/mode/julia");
        await import("brace/mode/kotlin");
        await import("brace/mode/latex");
        await import("brace/mode/less");
        await import("brace/mode/liquid");
        await import("brace/mode/lisp");
        await import("brace/mode/logiql");
        await import("brace/mode/lsl");
        await import("brace/mode/lua");
        await import("brace/mode/luapage");
        await import("brace/mode/lucene");
        await import("brace/mode/makefile");
        await import("brace/mode/markdown");
        await import("brace/mode/mask");
        await import("brace/mode/matlab");
        await import("brace/mode/maze");
        await import("brace/mode/mel");
        await import("brace/mode/mushcode");
        await import("brace/mode/mysql");
        await import("brace/mode/nix");
        await import("brace/mode/nsis");
        await import("brace/mode/objectivec");
        await import("brace/mode/ocaml");
        await import("brace/mode/pascal");
        await import("brace/mode/perl");
        await import("brace/mode/pgsql");
        await import("brace/mode/php");
        await import("brace/mode/powershell");
        await import("brace/mode/praat");
        await import("brace/mode/prolog");
        await import("brace/mode/properties");
        await import("brace/mode/protobuf");
        await import("brace/mode/python");
        await import("brace/mode/razor");
        await import("brace/mode/rdoc");
        await import("brace/mode/rhtml");
        await import("brace/mode/r");
        await import("brace/mode/rst");
        await import("brace/mode/ruby");
        await import("brace/mode/rust");
        await import("brace/mode/sass");
        await import("brace/mode/scad");
        await import("brace/mode/scala");
        await import("brace/mode/scheme");
        await import("brace/mode/scss");
        await import("brace/mode/sh");
        await import("brace/mode/sjs");
        await import("brace/mode/smarty");
        await import("brace/mode/snippets");
        await import("brace/mode/soy_template");
        await import("brace/mode/space");
        await import("brace/mode/sql");
        await import("brace/mode/sqlserver");
        await import("brace/mode/stylus");
        await import("brace/mode/svg");
        await import("brace/mode/swift");
        await import("brace/mode/tcl");
        await import("brace/mode/tex");
        await import("brace/mode/textile");
        await import("brace/mode/toml");
        await import("brace/mode/tsx");
        await import("brace/mode/twig");
        await import("brace/mode/typescript");
        await import("brace/mode/vala");
        await import("brace/mode/vbscript");
        await import("brace/mode/velocity");
        await import("brace/mode/verilog");
        await import("brace/mode/vhdl");
        await import("brace/mode/wollok");
        await import("brace/mode/xml");
        await import("brace/mode/xquery");
        await import("brace/mode/yaml");
        await import("brace/mode/abap");
        await import("brace/mode/abc");
        await import("brace/mode/actionscript");
        await import("brace/mode/lean");
        await import("brace/mode/live_script");
        await import("brace/mode/livescript");
        await import("brace/mode/mavens_mate_log");
        await import("brace/mode/mips_assembler");
        await import("brace/mode/mipsassembler");
        await import("brace/mode/swig");
        await import("brace/mode/diff");
        await import("brace/mode/plain_text");
        await import("brace/mode/text");
    },
};
